export { default as AboutUs } from "./AboutUs";
export { default as DetailedDescriptions } from "./DetailedDescriptions";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as OrderForm } from "./OrderForm";
export { default as OrderConfirmation } from "./OrderConfirmation";
export { default as Register } from "./Register";
export { default as RequestForm } from "./RequestForm";
export { default as Cart } from "./Cart";
